title: "Static, Meet Dynamic."
description:
combination: 
staticBenefits:
  - speed (cdn/pre-rendered)
  - cacheability
  - reliability
  - developer workflow
dynamicBenefits:
  - speed (ui/ux)
  - isomorphic rendering
  - complex state management
  - dynamic components
